name:                ogs-download
version:             0.1.0.0
github:              "djanatyn/ogs-download"
license:             BSD3
author:              "Jonathan Strickland"
maintainer:          "djanatyn@gmail.com"
copyright:           "2018 Jonathan Strickland"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Download .SGF files from online-go.com
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/djanatyn/ogs-download#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- aeson
- http-conduit
- http-client
- http-client-tls

library:
  source-dirs: src

executables:
  ogs-download:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ogs-download

tests:
  ogs-download-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ogs-download
